trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g newman
  displayName: 'Install Newman'

- script: newman run APIs.postman_collection.json -e WireWebhookEnv.postman_environment.json
  displayName: 'Run Newman Integration Test'